services:
  - type: web
    name: bot-trading
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web:app
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
