
services:
  - type: web
    name: telegram-bot-trading
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_trading.py"
    healthCheckPath: "/"
